language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- 1.8
install:
- ./tools/build.sh
- ./tools/package.sh
script:
- ./tools/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: oCXm7RDRNpzIEiTr17hWY21BvqT9uIH17ZmXlx7TL/0bTGdpNviNI5lFYdCYsJjf23lB4PDGaNiVHKsLso5GkF+tjDq6T/NmT94DBxGTHFXUam9fLoy6yKyGcE5zXM8VhVOL1V/dkZcw2KJD/85LbYuN8/uRxeW/U6QYvX4BlZlELGwUkni+reL8xm+c53WKRsxp+wNO7kzrrWkBppRmQ7gKASUE6MqKzGCojGQAkdr9F0BtBkBa4Zx/HEEQHO6vccCFx7xaeyOixdZHuppHFkLI6noyhDhunBYYUDBlt8aWTV5Qk8suNZcpTVmcQ+NY6aNXkzQQo1yX//f8OA02l9baVuucV6Y8jEzTUR9v2CNOBayhqih3EFe09jbVpywFraz9eEIgzgT9HKQeYxH8DGxgawR522jEmCj6VCJ6j2gNMBISCgJJYEP/VarWxzSFZ94NZ5KuFAwtgTyXt0xhMZyAgvd5y/FEDwBRhZp6sHz1tRsYRATYmLVOdCjmtZVk0lK0ffylFobhGQREkH3gN1rEZNep4CC7V8Bd5JFyIOrmJY8yWynnpWpKlyFF0PSH7bkWMRyvbq/D9C3D1mL9vgnAmCnS6JM0eyL2rVTdDtEjhmPDOTv9TVyhEtytUVWQ9UZaxRBaImOSATn8AKDzwNPsr4gDk4eGPwmJ6sCLw8Q=
  file:
  - terraform-provider-drp.zip
  - terraform-provider-drp.sha256
  - terraform.yaml
  - terraform.sha256
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
