language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- 1.9
git:
  depth: 500
install:
- ./tools/build.sh
- ./tools/package.sh
- ./tools/publish.sh
script:
- ./tools/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: lLId1X8veaG+UDFswB8CPIbWckwSWTUNynpjJ3Zy1eMHVOuathWhQilb9iKwpuzmWXJwojLOd8SviOAPnGGwvNcVYGGEI8QYwCCbrkZpmvS9zDKn5u6P8Y5mVfeLCUt2NugVCWMuP2bahab41Mhv2q5NXyxGoSI4oeWVWgpyHaKWO2Mr6rIMdrqjYH1mOsIGZrf0SeM6ABthhD3nrAp6/4eT1lX3gKeu++zJUJ26zcLFi3090niGHoCbxQpTd+ogjLga5S4c7J61Fv0OVlVb8jTYb2kxpPOp/mKDcn/3hmMHS2SBFIjq6PBZvLBOiMrZg8DzaJITWPzl76kmkYwbQ+LPB+wAmNubXso8/GGga/Zf14BryU7Gl8GhIAd3A0McFiXvRN3lWYiOgjJInrcqnw/khaBoImvv2oDm+lJORtdSOrITQ59iLizoHJxjbX5UlaIKMysUAeXjGBlxW7R0fKg9oKZ7bSxoARsLFxIgvfmdyuoIoLG8FqWanG9+DqGFCOg/M7J1LVL50kViokJSwByq5/n+0NebjCKceTvIBIE6/BIV9bma04gBoMI/h64GyRAN/S+IortEs0GO7h/DskSetuUFmNQnm4w+Yw/do026/XExysA5KYVvGsjw2Y1mTZw90OD/xuBG+kwjAfaDJIvG34QoNOBHmy+SvJTifIY=
  file:
  - terraform-provider-drp.zip
  - terraform-provider-drp.sha256
  - terraform.yaml
  - terraform.sha256
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
- provider: s3
  access_key_id: AKIAJF4QJY2A23DY6YTQ
  secret_access_key:
    secure: PpixFuFFHtvoOSmcF2HOF8ZSXqcnApxG65MDdDG/Cvt5wHf3KlpduhgsHK2+CaVIJ51giS9OzGCvV+269sqAKiFliGOSdNqQ5lGF5LSLpl+4Z4mikQvGGEgfIwjvWDJ2JmJ6RXPPMoxAZoDdlEg0h5AnSLsqvkzfqm27t/Wp9Vcz9CODQ5joLVGjcFLkEcFGhAn6ShOXqny2NJf3VzKUQFmsbEHK6H2f9JWDPqLaKf+DjgfqiK2ioDOWksTH0atnkt+nAEn3bR3TihgijvZKGe5BOxg+9Cm+2HgY4AFzW5FGHwOt3QbdyT4Dqy8U3pe9U1eNy/DuY7HWMP+lkWBbnD88vaeF8fwpMeicH9Qvv7v7QdRrYbiw1bVY60UCewoZejR67XYCXkbjIirBUojAlYTLCDfCjqxMP0Nby02eWql616a4IWW1v/nYu9AhvO1rc5SAWYwW8nSBtJSjEe3QBnxzMTTPpUJr0p3Wg/aEeH2NjUkDhSN9awoviMJsv7y1xtbAPFU1xdmxu0h7/CToetsV0sTX9XlG+afvVS2p77TW3dng0EjybTlOPY9f+GkS+1lSLLOElrMwojllte4/ZI0IKDYxjVw+z6T1GcOCGFhPs9l84SFHFKGc5rtzINg/J5j2lZUKVdXnSWh0acmzo0IFB4BmtlcVyWfZ9e/a2pE=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
